name: xcube-cds
channels:
  - conda-forge
dependencies:
  # Python
  - python >=3.9
  # Required
  - cdsapi >=0.7.2
  - jsonschema >=3.2.0
  - numpy >=1.17
  - pandas
  - python-dateutil >=2.8.1
  - xarray >=0.18.2
  - xcube >=0.9.0
  # Optional
  # for support of cftime with matplotlib (to run sea ice thickness notebook)
  - nc-time-axis >=1.4.1
