name: xcube-cds
channels:
  - conda-forge
  - defaults
dependencies:
  - cdsapi >=0.7.0
  - jsonschema >=3.2.0
  - numpy >=1.17
  - python-dateutil >=2.8.1
  - xarray >=0.18.2
  - xcube >=0.9.0
  # for support of cftime with matplotlib (required to run sea ice thickness notebook)
  - nc-time-axis >=1.4.1
